---
title: "Heat Map of President and Topics in the SOU Addresses"
author: "Peer Christensen"
date: "20/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r}
library(tidyverse)
library(tidytext)
library(topicmodels)
library(magrittr)
library(scales)
```

## The data

```{r}
df <- read_csv("state_of_the_union.csv")

names(df)

df
```

## Preparing the data

```{r}
exclude <- c("united","states","must","may","can")

df                                         %<>%
  unnest_tokens(word, text)                %>%
  anti_join(get_stopwords())               %>%
  filter(!str_detect(word, "[0-9]+ | NA")) %>%
  filter(!word %in% exclude)               %>%
  add_count(word)                          %>%
  filter(n > 10)                           %>%
  select(-n)

df
```

## Cast to document term matrix

```{r}
df_dtm_pres <- df               %>%
  count(president, word) %>%
  cast_dtm(president, word, n)

df_dtm_pres

str(df_dtm_pres)
```

## Fit LDA model (Latent Dirichlet Allocation)

```{r}
lda_model <- LDA(df_dtm_pres, k=30, method = "VEM")

lda_model
```

## Get posterior probabilities of topics for each president

```{r}
post_probs <- topicmodels::posterior(lda_model, df_dtm_pres)[["topics"]]

post_probs
```


## Basic heatmap

```{r}
heatmap(post_probs)
```

## Converting to a data frame

```{r}
heat_df <- post_probs             %>% 
  data.frame()                    %>%
  mutate(president = rownames(post_probs)) %>%
  mutate(president = unique(df$president))

heat_df
```

## Preparing the data (again)

```{r}
heat_df                                 %<>% 
  gather(topic, value, -president)      %>%
  mutate(topic = as.factor(as.numeric(str_replace(topic,"X",""))),
         president = factor(president)) %>%
  as_tibble()

heat_df$president <- factor(heat_df$president, levels = unique(df$president))

heat_df
```

## Heatmap with ggplot2!

```{r}
heat_df %>% ggplot(aes(topic,fct_rev(president))) + 
  geom_tile(aes(fill = value), colour = "snow") + 
  scale_fill_gradient(low = "snow", high = "darkred") +
  labs(title = "Topics associated with presidents",
       y     = "presidents") +
  theme_minimal()

#ggsave("heatmap.png")
```

## Explore topics

```{r}
td_beta <- tidy(lda_model)

top_terms <- td_beta          %>%
  mutate(term = recode(term, government = "govt")) %>%
  arrange(beta)                 %>%
  group_by(topic)               %>%
  top_n(6, beta)                %>%
  arrange(-beta)                %>%
  select(topic, term)           %>%
  summarise(terms = list(term)) %>%
  mutate(terms = map(terms, paste, collapse = ", ")) %>% 
  unnest()

td_gamma <- tidy(lda_model, matrix = "gamma",
                 document_names = rownames(df_dtm_pres))

gamma_terms <- td_gamma            %>%
  group_by(topic)                    %>%
  summarise(gamma = mean(gamma))     %>%
  arrange(desc(gamma))               %>%
  left_join(top_terms, by = "topic") %>%
  mutate(topic = paste0("Topic ", topic),
         topic = reorder(topic, gamma))

lda_plot <- gamma_terms %>%
  top_n(15, gamma)       %>%
  ggplot(aes(topic, gamma, label = terms, fill = topic)) +
  geom_col(show.legend = FALSE) +
  geom_text(hjust = -.05, size = 3, family = "Helvetica") +
  coord_flip() +
  scale_y_continuous(expand = c(0,0),
                     limits = c(0, .18),
                     labels = percent_format()) +
  labs(x        = NULL, 
       y        = expression(gamma),
       title    = "LDA: Top 15 topics by prevalence in the SOU",
       subtitle = "With the top words that contribute to each topic") +
  scale_fill_viridis_d(begin=.3)

lda_plot 

ggsave("lda_plot.png", width=10)
```
